# Do not change the 'definitions' section unless you know what you're doing
schematic:
  branch: 'empty'
  sha: 'empty'
  release_version: 'empty'

definitions:
  synapse_config: '.synapseConfig'
  creds_path: 'credentials.json'
  token_pickle: 'token.pickle'
  service_acct_creds: 'schematic_service_account_creds.json'

synapse:
  master_fileview: 'syn20446927'
  manifest_folder: 'manifests'
  manifest_basename: 'synapse_storage_manifest'
  token_creds: 'syn23643259'
  service_acct_creds: 'syn25171627'

manifest:
  # if making many manifests, just include name prefix
  title: 'example'
  # to make all manifests enter only 'all manifests'
  data_type:
    - 'Biospecimen'
    - 'Patient'

model:
  input:
    # Uncomment line below for staging
    #download_url: 'https://raw.githubusercontent.com/ncihtan/data-models/main/HTAN.model.jsonld'
    # Update line below for prod
    #download_url: 'https://raw.githubusercontent.com/ncihtan/data-models/v23.1.2/HTAN.model.jsonld'
    location: '.github/CSV.model.jsonld'
    file_type: 'local'

style:
  google_manifest:
    req_bg_color:
      red: 0.9215
      green: 0.9725
      blue: 0.9803
    opt_bg_color:
      red: 1.0
      green: 1.0
      blue: 0.9019
    master_template_id: '1LYS5qE4nV9jzcYw5sXwCza25slDfRA1CIg3cs-hCdpU'
    strict_validation: true
